### ISSUE TITLE
Commands not working after kickPlayer() & banPlayer()

### ISSUE THREAD

**Issue by 0FakE** [Nizarii/arma-rcon-class-php#12]
Grüße Felix,

die Arrays der Spieler und Bans werden nun korrekt dargestellt.
Wie ich gelesen habe, lag der Fehler ja doch im Suchmuster.

Nun aber zu einem anderen Problem:

Beim Senden eines Formulars bsp. um einen Spieler zu kicken,
wird die Funktion `kickPlayer()` erfolgreich ausgeführt. Seltsamerweise
geben alle anderen Funktionen, die nach `kickPlayer()` aufgerufen werden
nichts mehr zurück. Bsp. wird nach dem Senden des Formulars noch die
Spielertabelle durch `getPlayersArray()` geladen und gibt nix mehr zurück.

Der Descrutor ist dafür allerdings nicht verantwortlich.
Eine Auskommentierung hat in diesem Falle nichts bewirkt.

Ich verstehe nicht ganz, wieso die Verbindung offenbar getrennt ist.

Kannst du mir dazu etwas sagen?

**Übrigens sprachst du letztes mal davon, dass ich `close()` nicht verwenden
müsse und die Funktion privat sei, sie ist aber eine öffentliche Funktion.**
(das nur mal am Rande erwähnt...)

**Comment by felixms** [comment]
Nochmals danke für dein aufmerksames Feedback, ich bin derzeit nicht zu Hause und werde mich dem Problem annehmen sobald ich wieder zurück bin.

**Comment by felixms** [comment]
Problem ist behoben. Warum die anderen Funktionen nach kick-, bzw. banPlayer() nicht mehr funktionieren ist mir schleierhaft, jedoch wurde dies mit der neuen Funktion `reconnect()` gelöst. 

> Übrigens sprachst du letztes mal davon, dass ich close() nicht verwenden
> müsse und die Funktion privat sei, sie ist aber eine öffentliche Funktion.
> (das nur mal am Rande erwähnt...)

Ich bezog mich dabei auf die _Variable_ `$disconnected`, jedoch nicht auf die Funktion `close()`. Wie du schon gesagt hast, `close()` ist _public_ und kann jeder Zeit aufgerufen werden.

**Comment by felixms** [comment]
Problem translated: After running `kickPlayer()` or `banPlayer()` other functions, e.g. `sayGlobal()`, were broken. Fixed this issue by running `reconnect()` after the execution of these commands.

**Comment by 0FakE** [comment]
Vielen Dank für das schnelle Lösen des Problems.
Ich melde mich gern, solllten weitere Unklarheiten auftreten.
