### ISSUE TITLE
Connection - fatal error

### ISSUE THREAD

**Issue by 0FakE** [Nizarii/arma-rcon-class-php#13]
Hallöchen,

deine RCON Klasse spuckt mir seit dem letzten Update folgenden Fehler aus:

`Fatal error: Uncaught exception 'Exception' with message '[ARC] Wrong parameter type!'`

Witzigerweise entsprechen allerdings alle Parameter den Vorgaben `string` oder `int`.

`$rcon = new \Nizarii\ARC("255.255.255.255", 2353, "Passwort");`

IP und Passwort wurden natürlich geändert.
Kommentiere ich die folgende Überprüfung aus (inkl, `throw`)

`if ( !is_int($serverPort) || !is_string($RCONpassword) || !is_string($serverIP) )`

...kann plötzlich kein `socket` mehr erstellt werden.
Das Script scheitert an `fsockopen` also der Funtion `connect`.

**Comment by felixms** [comment]
Der Konstruktor wurde geändert, einfach Port und Passwort tauschen ;)
