### ISSUE TITLE
Functions not working after getPlayersArray()

### ISSUE THREAD

**Issue by Pacerino** [Nizarii/arma-rcon-class-php#20]
Hallo Felix!

wie du in einem [anderen Issue](https://github.com/Nizarii/arma-rcon-class-php/issues/12) beschrieben hast, funktionieren die Funktionen nicht mehr nachdem eine andere bereits aufgerufen wurde. Du hast dies mit dem Befehl _$this->reconnect();_ gelöst doch nicht überall eingetragen.

Heute musste ich leider feststellen dass die Funktion _getPlayersArray()_ ebenfalls dieses Problem aufweist.
Kurzerhand wurde dies aber gelöst durch ein einfaches einfügen von _$this->reconnect();_ über _return players;_

Gruß und schönes Wochenende,
Pac

**Comment by felixms** [comment]
Danke für den Hinweis! 👍
