### ISSUE TITLE
sayPlayer Wrong Parameters

### ISSUE THREAD

**Issue by cat24max** [Nizarii/arma-rcon-class-php#21]
Am I stupid?
I am providing an integer for the player and a message as a string and the answer I get is "Wrong parameter type(s)!"

Am I doing something wrong?

**Comment by felixms** [comment]
Mmh, something must be wrong with your code :/ This snippet validates the parameter types:
```php
if (!is_int($player) || !is_string($message)) {
       throw new \Exception('Wrong parameter type(s)!');
}
```

**Comment by felixms** [comment]
If you are 100% sure, that your types are correct, you can work around by sending the command "manually":
```php
$arc->command("Say $player $message")
```

**Comment by cat24max** [comment]
I have just double checked my types...
The player ID is even intval()'ed before and the message is a string.
I am sending the command over a JSON api, so I'll have to look into that again.

**Comment by cat24max** [comment]
Anyway, it works with the manual say command
