### ISSUE TITLE
Error Ban Arma 3

### ISSUE THREAD

**Issue by Milou544** [Nizarii/arma-rcon-class-php#3]
Hello, I have a problem with the ability to ban a player.

`
$rcon->ban_player('f276e058bbaaff85d23070c9bd43e2aa', 'test', 30);
`

`Return true`

But at the console is not banned. We see just that it is logged

**Comment by felixms** [comment]
The command is sent properly (see [here](https://community.bistudio.com/wiki/BattlEye#GUID_banning)), looks like a server side fault to me.
