### ISSUE TITLE
RCON Console

### ISSUE THREAD

**Issue by fruityrooty** [Nizarii/arma-rcon-class-php#35]
Hey buddy, i'm trying to build a live console in the browser to monitor chat.
We've tried it using the socketLoop function, and using reconnect(); sadly enough without success, in the end we did manage to read one of the lines (the Rcon Admin logged in), but then it closes the socket.
Do you have an example how to do this?

**Comment by nerdalertdk** [comment]
Answer should be in here 

https://github.com/schaeferfelix/arma-rcon-class-php/issues/30

**Comment by steffalon** [comment]
Hi @fruityrooty, Did you use socketloop(**-1**)? Also you could try using SSE (Server-Send Event) method. Also maybe socket.io websocket could be interesting. If you create php websocket server and ARC as middleware,  you can read realtime server output without any SSE downsides.

I made a SSE example here: #31

**Comment by felixms** [comment]
Issue closed because of inactivity.
