### ISSUE TITLE
Fatal error: Uncaught Exception: Wrong constructor parameter type(s)! 

### ISSUE THREAD

**Issue by GhostikGER** [Nizarii/arma-rcon-class-php#39]
Hallo,

ich hab echt lange Probiert.
Egal welche Zugänge ich eingebe, er gibt mir jedesmal die Fehlermeldung:

> Fatal error: Uncaught Exception: Wrong constructor parameter type(s)!

` $rcon = new ARC('12.123.123.12', 'Passwort', '2903');
        $array = $rcon->getPlayersArray();
        debug($array);`

Wenn ich allerdings die Zugangsdaten mit einem RCON Programm von 2014 öffne, kann ich mich direkt verbinden! Ist die Version mittlerweile zu alt?

LG Max

**Comment by nerdalertdk** [comment]
'2903' should be 2903

The error says you have the wrong type in the paramenter, the port is an int not an string
