### ISSUE TITLE
 No Connection und Loading Time

### ISSUE THREAD

**Issue by felixsch28** [Nizarii/arma-rcon-class-php#40]
Hi.
Sometimes the connection stops and when I am reloading the site, it says: no connection, wrong login data or something like that.

But my main problem is, that my website loads very long. When there are 5 players the site loads really fast but when the server got about 60 to 80 players, the site take 8 seconds to load until it's ready. Maybe you got a good solution to list all players without waiting my hole life.

~ Felix

**Comment by felixms** [comment]
Caching. 
Hope you find any use with that answer, considering it being so late! 😅  

~ Felix :)

**Comment by felixms** [comment]
Feel free to open the issue again, if you still have any questions.
