### ISSUE TITLE
Web console help

### ISSUE THREAD

**Issue by realBlxcky** [Nizarii/arma-rcon-class-php#42]
Guten Tag Felix, 
erstmal danke das du eine so schöne API hier hast
aber kommen wir mal zum wichtigen ich würde gerne eine Web Rcon Console machen 
könntest du mir evt. sagen wie es geht ich bin via Discord erreichbar  Blxcky | Fabian#4724 
danke :D

**Comment by felixms** [comment]
Hallo! Sollte es Dir rein um die Funktionalität gehen, empfehle ich Dir bereits vorhandene, etablierte Software zu nutzen. Wenn Du nun aber selbst basteln willst, solltest Du folgende Punkte beachten:
- das einfache Senden von Befehlen, auch oder gerade mit Browser input ist kein Probelm
- alles was darüber hinaus geht, wie zB. das Aufzeichnen von eingegangenen Nachrichten (History), wird durch PHP/ARC nur unnötig verkompliziert
- für eine vollständige Konsole solltest du Dich ua. über das Thema Daemons und WebSockets schlau machen, da eine ständige Verbindung zum Server benötigt wird
- Thema "Ständige Verbingung" s. NodeJs ua. Sprachen welche sich besser dazu eignen

> könntest du mir evt. sagen wie es geht 

Ich hoffe ich konnte Dir mit obigem _etwas_ weiterhelfen. Aus Zeitmangel kann ich Dir leider nicht viel mehr entgegenkommen. Ich schließe das Ganze hier mal, bei konkreten Fragen kannst Du aber natürlich gerne hierauf antworten.
