### ISSUE TITLE
Login fails with some rcon passwords

### ISSUE THREAD

**Issue by Ruslan-700** [Nizarii/arma-rcon-class-php#45]
Login fails with some rcon passwords, eg **DA5JQxtvFZO**
Tested on Dayz Standalone servers.

**Comment by JakeLBeans** [comment]
Also having this issue. Spent a good hour thinking I'm missing something silly but it's definitely not wrong.

**Comment by Ruslan-700** [comment]
Check my pull request
apparently the project is already abandoned

**Comment by JakeLBeans** [comment]
@Ruslan-700 you're a legend! Thank you!

**Comment by felixms** [comment]
Thank you very much @Ruslan-700 for helping out! 👏 I merged your pull request #47.
