### ISSUE TITLE
Fatal Error Class Nizarii\ARC not Found

### ISSUE THREAD

**Issue by realBlxcky** [Nizarii/arma-rcon-class-php#46]
Guten Tag, ich wollte mir gerade das ARC wieder auf setzen aber bekomme immer diesen Fehler wenn ich eine neue verbindung aufbauen will

Fatal error: Uncaught Error: Class 'Nizarii\ARC' not found in C:\xampp\htdocs\rcon\test.php:5 Stack trace: #0 {main} thrown in C:\xampp\htdocs\rcon\test.php on line 5

Ich versuche eine Verbindung wie über das Beispiel herzustellen aber es funktioniert nicht könnten sie mir helfen?

**Comment by felixms** [comment]
Ohne deine Datei `test.php` gesehen zu haben, würde ich schwer behaupten, dass du ARC falsch, bzw. erst garnicht importiert hast. 

Versuchs mal `require_once 'DEIN_PFAD_ZUR_DATEI/arc.php';`
oder nutze einfach den Autoloader von Composer.

Ich schließe diesen Thread mal bis auf weiteres. Sollte noch was unklar sein, kannst du ihn gerne wieder aufmachen.

**Comment by MrBlackZombieHD** [comment]
<?php 
require_once 'arc.php';

try {
    $rcon = new ARC('127.0.0.1', 'password');
       
    $array = $rcon->getPlayersArray();
    
    $rcon
        ->sayGlobal('example')
        ->kickPlayer(1, 'example')
        ->sayPlayer(0, 'example')
        ->disconnect()
    ;
    
    $rcon->getBans(); // Throws exception, because the connection was closed
} catch (Exception $e) {
    echo "Ups! Something went wrong: {$e->getMessage()}";
}
?>



Das ist meine Test PHP wie sie in ihren Beispiel ist

**Comment by felixms** [comment]
Da fehlen doch ein paar Zeilen am Anfang oder? Wenn nein würde mich wundern, dass du überhaupt zu dem Fehler gekommen bist.
Ich verweise nochmal darauf:
> Ohne deine Datei test.php gesehen zu haben, würde ich schwer behaupten, **dass du ARC falsch, bzw. erst garnicht importiert hast.**
>Versuchs mal require_once 'DEIN_PFAD_ZUR_DATEI/arc.php';
oder nutze einfach den Autoloader von Composer. 

Du solltest vllt mal nachlesen, wie man libraries in PHP importiert.

**Comment by MrBlackZombieHD** [comment]
<?php 
require_once 'arc.php';

try {
    $rcon = new ARC('127.0.0.1', 'password');
       
    $array = $rcon->getPlayersArray();
    
    $rcon
        ->sayGlobal('example')
        ->kickPlayer(1, 'example')
        ->sayPlayer(0, 'example')
        ->disconnect()
    ;
    
    $rcon->getBans(); // Throws exception, because the connection was closed
} catch (Exception $e) {
    echo "Ups! Something went wrong: {$e->getMessage()}";
}
?>

**Comment by realBlxcky** [comment]
`<?php 
require_once 'arc.php';

try {
    $rcon = new ARC('127.0.0.1', 'password');
       
    $array = $rcon->getPlayersArray();
    
    $rcon
        ->sayGlobal('example')
        ->kickPlayer(1, 'example')
        ->sayPlayer(0, 'example')
        ->disconnect()
    ;
    
    $rcon->getBans(); // Throws exception, because the connection was closed
} catch (Exception $e) {
    echo "Ups! Something went wrong: {$e->getMessage()}";
}
?>` Hier bitte noch einmal

**Comment by felixms** [comment]
Du verwendest den [namespace](https://www.php.net/manual/de/language.namespaces.php) nicht.

```
<?php
require_once 'arc.php';

use \Nizarii\ARC;

try {
..
```
