### ISSUE TITLE
Feature Request: Show mission name + player time connected

### ISSUE THREAD

**Issue by alexcroox** [Nizarii/arma-rcon-class-php#6]
I've switched from the [Source Query](https://github.com/xPaw/PHP-Source-Query) library because that one can't return BE GUID for players. However I still have to use it for certain info I wondered if possible to also gain through RCON in this library:
- Mission name
- Player connected time

**Comment by felixms** [comment]
I'm sorry to disappoint you, but as far as I know, this is not possible with RCon. See this [wiki article](https://community.bistudio.com/wiki/BattlEye#RCon_commands). I may integrate the Source Query library in order to get query informations too as needed.

**Comment by alexcroox** [comment]
Fair enough, thanks for looking into it :)

**Comment by Memphis017** [comment]
You should have a look at this library instead of Source Query : [https://github.com/Austinb/GameQ](url) which have everything you want (except GUID which is, to my knowledge, only provided by RCon because it's BattlEye stuff).

**Comment by alexcroox** [comment]
Nice thank you. Source Query is already giving me everything I need (that I can't get from RCON) so it was a matter of trying to find a library that has it all instead of replacing like for like. I'll still have to make 3 queries for player connected time, mission name, player GUIDs. I appreciate that this is out of the scope of this library as it's not possible from RCON alone :)
