### ISSUE TITLE
getPlayersArray Funktioniert nicht.

### ISSUE THREAD

**Issue by D3RFLO** [Nizarii/arma-rcon-class-php#9]
Hi, die Neue API funktioniert soweit ganz gut. Allerdings wenn ich die Spieler in einem Array haben will: `$players = $rcon->getPlayersArray();` und sie dann Test weise mit mit print_r `print_r($players);` ausgeben will sieht man auf der Seite einfach nur `Array ( )`

**Comment by felixms** [comment]
mmh, kurz mal ne doofe Frage, aber ist das mit `getBansArray()`  das gleiche? Ich schau mir mal die Funktionen an, zeigt dir bei der Ausführung PHP einen Fehler/Notice an?

**Comment by D3RFLO** [comment]
Wenn ich `getBansArray()` versuche kommt das gleiche. Es kommt auch keine Fehler/Notice Meldung

**Comment by felixms** [comment]
Ok danke. Ich schau mal ob mir etwas ins Auge fällt, testen kann ich aktuell jedoch leider nichts. :/

**Comment by D3RFLO** [comment]
Ok, vielen dank ;)

**Comment by felixms** [comment]
Mir ist bis jetzt nichts Ungewöhnliches aufgefallen, bis auf https://github.com/Nizarii/arma-rcon-class-php/blob/master/arc.php#L532. Kannst bitte mal die Funktion `formatList` durch [diese hier](https://gist.github.com/Nizarii/3c5961d82f8a02e6ea2024b132ef5f52) ersetzten? Vielen Dank schon mal im voraus! :+1:

**Comment by D3RFLO** [comment]
Habe ich gemacht, funktioniert leider immer noch nicht.

**Comment by felixms** [comment]
Wie viele Spieler sind den auf dem Server wenn du das testest? Rein theoretisch müsste der code nämlich funktionieren :/

**Comment by D3RFLO** [comment]
Nur ich. Kann es vielleicht daran liegen das ich `print_r` benutze? (Um es im Moment nur zu testen)

**Comment by felixms** [comment]
An `print_r` sollte es nicht liegen :/ Kannst du das ganze testen mit mehr als einer Person auf dem Server? Sofern es natürlich nicht zu umständlich wäre ^^ Ich würde mich auch zur Verfügung stellen um dem Server zu joinen, bei Interesse, hier mein [Steam-Profil](http://steamcommunity.com/id/nizarii/).

**Comment by D3RFLO** [comment]
Wäre echt nett. Du könntest auf den Teamspeak: 194.169.211.51:11500 Kommen. Ich bin aber jetzt gleich für ca. 1 Stunde weg, wir könnten es Testen wenn ich wieder da bin.
